import type { Form } from "./types/form";

/**
 * Mock forms data for development and testing.
 * This data simulates what would be returned from a forms API.
 */
export const mockForms: Form[] = [
	{
		id: "1",
		name: "Customer Onboarding Form",
		nameEs: "Formulario de Incorporación de Clientes",
		description:
			"Collect essential information from new customers during the onboarding process",
		descriptionEs:
			"Recopile información esencial de nuevos clientes durante el proceso de incorporación",
		status: "published",
		currentVersion: 3,
		createdAt: "2024-01-15T10:00:00Z",
		updatedAt: "2024-03-20T14:30:00Z",
		tags: ["onboarding", "customer", "high-priority"],
		versions: [
			{
				id: "v1-1",
				version: 1,
				createdAt: "2024-01-15T10:00:00Z",
				createdBy: "Sarah Johnson",
				changelog: "Initial form creation",
				fields: [
					{
						id: "f1",
						type: "name",
						label: "Full Name",
						labelEs: "Nombre Completo",
						placeholder: "Enter your full name",
						placeholderEs: "Ingrese su nombre completo",
						required: true,
					},
					{
						id: "f2",
						type: "email",
						label: "Email Address",
						labelEs: "Dirección de Email",
						placeholder: "you@example.com",
						placeholderEs: "usted@ejemplo.com",
						required: true,
					},
				],
				schema: {
					input: {},
					output: { fullName: "string", email: "string" },
				},
			},
			{
				id: "v1-2",
				version: 2,
				createdAt: "2024-02-10T11:20:00Z",
				createdBy: "Mike Chen",
				changelog: "Added phone and address fields",
				fields: [
					{
						id: "f1",
						type: "name",
						label: "Full Name",
						labelEs: "Nombre Completo",
						placeholder: "Enter your full name",
						placeholderEs: "Ingrese su nombre completo",
						required: true,
					},
					{
						id: "f2",
						type: "email",
						label: "Email Address",
						labelEs: "Dirección de Email",
						placeholder: "you@example.com",
						placeholderEs: "usted@ejemplo.com",
						required: true,
					},
					{
						id: "f3",
						type: "phone",
						label: "Phone Number",
						labelEs: "Número de Teléfono",
						placeholder: "+1 (555) 000-0000",
						placeholderEs: "+1 (555) 000-0000",
						required: true,
					},
					{
						id: "f4",
						type: "address",
						label: "Street Address",
						labelEs: "Dirección de Calle",
						placeholder: "Enter your address",
						placeholderEs: "Ingrese su dirección",
						required: false,
					},
				],
				schema: {
					input: {},
					output: {
						fullName: "string",
						email: "string",
						phone: "string",
						address: "string",
					},
				},
			},
			{
				id: "v1-3",
				version: 3,
				createdAt: "2024-03-20T14:30:00Z",
				createdBy: "Sarah Johnson",
				changelog: "Added communication preferences",
				fields: [
					{
						id: "f1",
						type: "name",
						label: "Full Name",
						labelEs: "Nombre Completo",
						placeholder: "Enter your full name",
						placeholderEs: "Ingrese su nombre completo",
						required: true,
					},
					{
						id: "f2",
						type: "email",
						label: "Email Address",
						labelEs: "Dirección de Email",
						placeholder: "you@example.com",
						placeholderEs: "usted@ejemplo.com",
						required: true,
					},
					{
						id: "f3",
						type: "phone",
						label: "Phone Number",
						labelEs: "Número de Teléfono",
						placeholder: "+1 (555) 000-0000",
						placeholderEs: "+1 (555) 000-0000",
						required: true,
					},
					{
						id: "f4",
						type: "address",
						label: "Street Address",
						labelEs: "Dirección de Calle",
						placeholder: "Enter your address",
						placeholderEs: "Ingrese su dirección",
						required: false,
					},
					{
						id: "f5",
						type: "checkbox-group",
						label: "Communication Preferences",
						labelEs: "Preferencias de Comunicación",
						required: false,
						options: [
							"Email Updates",
							"SMS Notifications",
							"Phone Calls",
							"Newsletter",
						],
					},
				],
				schema: {
					input: {},
					output: {
						fullName: "string",
						email: "string",
						phone: "string",
						address: "string",
						preferences: "array",
					},
				},
			},
		],
	},
	{
		id: "2",
		name: "Employee Feedback Survey",
		nameEs: "Encuesta de Retroalimentación de Empleados",
		description:
			"Quarterly survey to gather employee satisfaction and feedback",
		descriptionEs:
			"Encuesta trimestral para recopilar satisfacción y retroalimentación de empleados",
		status: "published",
		currentVersion: 2,
		createdAt: "2024-02-01T09:00:00Z",
		updatedAt: "2024-03-15T16:45:00Z",
		tags: ["hr", "feedback", "quarterly"],
		versions: [
			{
				id: "v2-1",
				version: 1,
				createdAt: "2024-02-01T09:00:00Z",
				createdBy: "Alex Rivera",
				changelog: "Initial survey creation",
				fields: [
					{
						id: "f1",
						type: "name",
						label: "Employee Name",
						labelEs: "Nombre del Empleado",
						placeholder: "Your name",
						placeholderEs: "Su nombre",
						required: true,
					},
					{
						id: "f2",
						type: "radio",
						label: "Overall Satisfaction",
						labelEs: "Satisfacción General",
						required: true,
						options: [
							"Very Satisfied",
							"Satisfied",
							"Neutral",
							"Dissatisfied",
							"Very Dissatisfied",
						],
					},
					{
						id: "f3",
						type: "text",
						label: "Additional Comments",
						labelEs: "Comentarios Adicionales",
						placeholder: "Share your thoughts...",
						placeholderEs: "Comparta sus pensamientos...",
						required: false,
					},
				],
				schema: {
					input: { employeeId: "string", department: "string" },
					output: {
						employeeName: "string",
						satisfaction: "string",
						comments: "string",
					},
				},
			},
			{
				id: "v2-2",
				version: 2,
				createdAt: "2024-03-15T16:45:00Z",
				createdBy: "Alex Rivera",
				changelog: "Added work-life balance question",
				fields: [
					{
						id: "f1",
						type: "name",
						label: "Employee Name",
						labelEs: "Nombre del Empleado",
						placeholder: "Your name",
						placeholderEs: "Su nombre",
						required: true,
					},
					{
						id: "f2",
						type: "radio",
						label: "Overall Satisfaction",
						labelEs: "Satisfacción General",
						required: true,
						options: [
							"Very Satisfied",
							"Satisfied",
							"Neutral",
							"Dissatisfied",
							"Very Dissatisfied",
						],
					},
					{
						id: "f3",
						type: "radio",
						label: "Work-Life Balance",
						labelEs: "Equilibrio Trabajo-Vida",
						required: true,
						options: ["Excellent", "Good", "Fair", "Poor"],
					},
					{
						id: "f4",
						type: "text",
						label: "Additional Comments",
						labelEs: "Comentarios Adicionales",
						placeholder: "Share your thoughts...",
						placeholderEs: "Comparta sus pensamientos...",
						required: false,
					},
				],
				schema: {
					input: { employeeId: "string", department: "string" },
					output: {
						employeeName: "string",
						satisfaction: "string",
						workLifeBalance: "string",
						comments: "string",
					},
				},
			},
		],
	},
	{
		id: "3",
		name: "Event Registration Form",
		nameEs: "Formulario de Registro de Eventos",
		description: "Registration form for company events and conferences",
		descriptionEs:
			"Formulario de registro para eventos y conferencias de la empresa",
		status: "draft",
		currentVersion: 1,
		createdAt: "2024-03-25T13:00:00Z",
		updatedAt: "2024-03-25T13:00:00Z",
		tags: ["events", "registration"],
		versions: [
			{
				id: "v3-1",
				version: 1,
				createdAt: "2024-03-25T13:00:00Z",
				createdBy: "Jennifer Lee",
				changelog: "Initial draft",
				fields: [
					{
						id: "f1",
						type: "name",
						label: "Attendee Name",
						labelEs: "Nombre del Asistente",
						placeholder: "Full name",
						placeholderEs: "Nombre completo",
						required: true,
					},
					{
						id: "f2",
						type: "email",
						label: "Email",
						labelEs: "Correo Electrónico",
						placeholder: "email@company.com",
						placeholderEs: "correo@empresa.com",
						required: true,
					},
					{
						id: "f3",
						type: "checkbox",
						label: "I agree to the terms and conditions",
						labelEs: "Estoy de acuerdo con los términos y condiciones",
						required: true,
					},
				],
				schema: {
					input: { eventId: "string", eventName: "string" },
					output: {
						attendeeName: "string",
						email: "string",
						agreed: "boolean",
					},
				},
			},
		],
	},
];
